config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/top_twenty'

  get '/login' => 'session#new'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'

  get '/' => 'welcome#index'
  get '/new' => 'users#new'
  post '/users/:user_id/users' => 'users#create'

  get '/tracks/:user_id/tracks'  => 'tracks#index'
  post '/tracks/:user_id/tracks' => 'tracks#create'
  put '/tracks/:user_id/tracks/:id' => 'tracks#edit'
end

app/models/track.rb
class Track < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # def new
  # end

  def create
    user = User.find_by(email_address: params[:email_address])

    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to "/tracks/"+user.id.to_s+"/tracks"
    else
      redirect_to '/'
    end
  end

  def destroy
    reset_session
    redirect_to '/login'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'soundcloud'
  def top_twenty
    # sc = SoundCloudWrapper.new
    client_id = ENV["SOUNDCLOUD_CLIENT_ID"]
    client = SoundCloud.new(:client_id => client_id)
    tracks = client.get('/tracks', :limit => 20, :order => 'hotness')
    @tracks = []
    tracks.each do |track|
      t = Track.create( title: track["title"], 
                   permalink_url:track["permalink_url"], 
                   description:track["description"] , 
                   avatar_url:track["user"]["avatar_url"] )
      @tracks << t
    end

  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end


  def create
    new_track = Track.create({
      title: params["title"],
      permalink_url: params["permalink_url"],
      description: params["description"],
      avatar_url: params["avatar_url"],
      user_id: params["user_id"],
    })
    redirect_to "/tracks/:user_id/tracks"
  end

  def edit
    @id = params["id"]
    @track = Track.find(params["id"])
    @user = @track.user_id
  end


  def destroy
    track = Track.find(params[:id])
    track.destroy
    redirect_to "/tracks/:user_id/tracks"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
 		User.create({
 			name: params["name"],
 			email_address: params["email_address"],
 			password: params["password"],
 			location: params["location"],
 			favorite_artist: params["favorite_artist"]
 			})
 		redirect_to "/"
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thunderhat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/top_twenty.html.erb
<h1>Top 20 Songs</h1>
<ul>
<% @tracks.each do |t| %>
  <li>
  <%= t.title %>
  <%= link_to t.title, t.permalink_url %>
  </li>
<% end %>
</ul>

app/views/tracks/edit.html.erb
<form method="POST" action=<%="/tracks/:user_id/tracks/" + @id %>>
	<input type="hidden" name="_method" value="PUT"/>
		NEW NAME
		<input type="text" name="name"/>
		NEW GENRE
		<input type="text" name="genre"/>
		currently_relevant?
		<select name="currently_relevant">
  			<option value="true">YES</option>
  			<option value="false">NO</option><br>
  		</select>
		<input type="hidden" name="id" value=<%=@id%>/>
		<input type="submit"/>
</form>
<br>
or
<br>
<br>
<form method="POST" action=<%="/bands/" + @id %>>
	<input type="hidden" name="_method" value="DELETE"/>
		<input type="hidden" name="id" value=<%=@id%>/>
		<button>DELETE BAND</button>

app/views/tracks/index.html.erb
<html>
<head>
	<title></title>
</head>
<body>
  <p><%= link_to "Top 20", static_pages_top_twenty_path %></p>
<p><%= @user.name %>, here are your tracks:</p>
	<form method="POST" action="/tracks/:user_id/tracks">
		<input name="title" type="hidden" value="title"/>
		
		<input name="permalink_url" type="hidden" value="permalink_url"/>
		
		<input name="description" type="hidden" value="description"/>
		
		<input name="avatar_url" type="hidden"value="avatar_url"/>
		
		<input name="user_id" type="hidden" value="user_id"/>

  		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
		<button>Save</button>
	
	</form>
</body>
</html>

app/views/users/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Create a new account</h1>
	<br>

	<form method="POST" action="/users/:user_id/users">
		NAME
		<input type="text" name="name"/>
		email
		<input type="text" name="email_address"/>
		password
		<input type="text" name="password"/>
		location
		<input type="text" name="location"/>
  		favorite artist
		<input type="text" name="favorite_artist"/>
		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
		<input type="submit"/>
	</form>
</body>
</html>

app/views/welcome/index.html.erb
<html>
<head>
	<title></title>
</head>
<body>
<form action="/session" method="POST">
  <label>
    Email:
    <input type="text" name="email_address" />
  </label>

  <label>
    Password:
    <input type="text" name="password" />
  </label>

  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <button>Sign In</button>

 <br>
 <br>
  <a href="/new">Create New Account
</form>
</body>
</html>